"""auto created date added in models

Revision ID: 02
Revises: 01
Create Date: 2023-02-28 10:53:22.576519

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '02'
down_revision = '01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
